### ISSUE TITLE
这个咋办

### ISSUE THREAD

**Issue by kai7850** [runner404/switch-#1]
Traceback (most recent call last):
  File "D:\desktop\-chatgpt-vpn-main\outlook_vpn_register.py", line 14, in <module>
    username = driver.find_element("name","MemberName")
  File "D:\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "D:\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "D:\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [name="MemberName"]
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16

进程已结束，退出代码 1

**Comment by runner404** [comment]
用火狐浏览器，不要用chrome
